on:
  push:
  pull_request:
    branches:
      - main

name: Test make prepare_offline

jobs:
  noas-offline-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,  r: '3.6'}
          - {os: ubuntu-latest,  r: '4.3'}
          - {os: ubuntu-20.04,   r: '3.6'}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        id: install-r
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Prepare offline
        run: make prepare_offline 

