on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Test make builds

jobs:
  noas-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,  r: '3.6'}
          - {os: ubuntu-latest,  r: '4.3'}
          - {os: ubuntu-18.04,   r: '3.6'}
          - {os: ubuntu-20.04,   r: '3.6'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        id: install-r
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Make 3rdparty
        run: make 3rdparty

      - name: Run & Import DB
        run: |
          make run_db &
          P1=$!
          make run_dbimport &
          P2=$!
          wait $P2




