on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Test make offline

jobs:
  noas-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: ubuntu-18.04,   r: 'release'}
          - {os: ubuntu-18.04,   r: '3.5'}
          - {os: ubuntu-20.04,   r: 'release'}
          - {os: ubuntu-20.04,   r: 'devel'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        id: install-r
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Prepare offline
        run: make prepare_offline

      - name: Try starting DB
        run: make run_db

      - name: Import DB
        run: make run_dbimport

      - name: Test webui
        run: timeout 1 make run_webui || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

