on:
  push:
  pull_request:
    branches:
      - main

name: Test make builds

jobs:
  noas-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,  r: '3.6'}
        #   - {os: ubuntu-latest,  r: '4.3'} # RPostgreSQL issue
          - {os: ubuntu-20.04,   r: '3.6'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4


      - name: Cache Built Artifacts
        uses: actions/cache@v4
        with:
            path: 3rdparty
            key: ${{ runner.os }}-3rdparty-${{ matrix.config.os }}-${{ matrix.config.r }}-${{ hashFiles('Makefile', '3rdparty/**/Makefile', '3rdparty/**/*.mk') }}
            restore-keys: |
              ${{ runner.os }}-3rdparty-${{ matrix.config.os }}-${{ matrix.config.r }}-
        

      - uses: r-lib/actions/setup-r@v2
        id: install-r
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Make 3rdparty
        run: make 3rdparty

      - name: Start DB
        run: |
          make run_db &
          sleep 30

      - name: Run & Import DB
        run: |
          set -e  # Enable error handling
          make run_dbimport
